CREATE TABLE members (
id INT AUTO_INCREMENT PRIMARY KEY,
full_name VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
number_phone TEXT NOT NULL,
uname VARCHAR(50) NOT NULL,
pass VARCHAR(50) NOT NULL
);